version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - my_net

  kafka:
    image: bitnami/kafka:3.5.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - my_net

  vuln-web:
    build: ./vuln-web
    ports:
      - "5000:5000"
    volumes:
      - ./vuln-web/app.py:/app/app.py
    networks:
      - my_net

  producer:
    build: ./producer
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
      - vuln-web
    networks:
      - my_net

  consumer:
    build: ./consumer
    environment:
      - KAFKA_BROKER=kafka:9092
    volumes:
      - ./passwords.db:/app/passwords.db
    depends_on:
      - kafka
    networks:
      - my_net

  # --- 新增：可视化仪表盘 ---
  dashboard:
    build: ./dashboard
    ports:
      - "5001:5000"  # 外部访问端口 5001
    volumes:
      # 关键：挂载同一个数据库文件，实现数据共享
      - ./passwords.db:/app/passwords.db
    networks:
      - my_net

networks:
  my_net:
    driver: bridge
